---
- hosts: 127.0.0.1
  tasks:
    - name:
      ansible.builtin.shell:
        PUBLIC_IP_ADDRESS=$(az network public-ip show -g kubernetes -n {{item.name}}-pip --query "ipAddress" -o tsv)
        scp -o StrictHostKeyChecking=no ../cert-keys/ca.pem ../cert-keys/{{item.name}}-key.pem ../cert-keys/{{item.name}}.pem kuberoot@${PUBLIC_IP_ADDRESS}:~/
      loop:
        - name: worker-0
        - name: worker-1
