---
- hosts: 127.0.0.1
  tasks:
    - name: Sending keys to controller nodes
      ansible.builtin.shell: |
        PUBLIC_IP_ADDRESS=$(az network public-ip show -g kubernetes -n {{item.name}}-pip --query "ipAddress" -o tsv)
        scp -i ${HOST_KEY}/{{item.name}}.pem -o StrictHostKeyChecking=no ${KEY_PATH}/ca.pem ${KEY_PATH}/ca-key.pem ${KEY_PATH}/kubernetes-key.pem ${KEY_PATH}/kubernetes.pem ${KEY_PATH}/service-account-key.pem ${KEY_PATH}/service-account.pem kuberoot@${PUBLIC_IP_ADDRESS}:~/
      loop:
        - name: controller-0
        - name: controller-1
        - name: controller-2
      environment:
        KEY_PATH: ../cert-keys
        HOST_KEY: ../../aks-keys
