# Validating that Terraform and Ansible code is proper
name: Validation

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - '*'
# validations only need to read
permissions: 
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Terraform Validation
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    strategy:
      fail-fast: false
      matrix:
        # list whatever Terraform versions here you would like to support
        terraform:
          - '1.2.*'
          - '1.3.*'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform Version Matrix
        uses: hashicorp/setup-terraform@v2
        with:
            terraform_version: ${{ matrix.terraform }}
            terraform_wrapper: false
      
      - name: Run Terraform Plan
        env:
            TF_ACC: "1"
        run: |
            make -C terraform/ plan
        timeout-minutes: 10

  ansible:
    runs-on: ubuntu-latest
    name: ansible-checks
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run an Ansible Check On Playbooks
        run: |
            make -C ansible/ check
        timeout-minutes: 10
